#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nanoflann
Version  : 1.3.1
Release  : 1
URL      : https://github.com/jlblancoc/nanoflann/archive/v1.3.1/nanoflann-1.3.1.tar.gz
Source0  : https://github.com/jlblancoc/nanoflann/archive/v1.3.1/nanoflann-1.3.1.tar.gz
Summary  : nanoflann - A C++11 header-only library for kd-trees
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nanoflann-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : eigen-dev

%description
![nanoflann](https://raw.githubusercontent.com/jlblancoc/nanoflann/master/doc/logo.png)

%package dev
Summary: dev components for the nanoflann package.
Group: Development
Provides: nanoflann-devel = %{version}-%{release}
Requires: nanoflann = %{version}-%{release}

%description dev
dev components for the nanoflann package.


%package license
Summary: license components for the nanoflann package.
Group: Default

%description license
license components for the nanoflann package.


%prep
%setup -q -n nanoflann-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571087664
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1571087664
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nanoflann
cp %{_builddir}/nanoflann-1.3.1/COPYING %{buildroot}/usr/share/package-licenses/nanoflann/525a4173096d5a839c3d609ae433ba90f2275dea
cp %{_builddir}/nanoflann-1.3.1/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/nanoflann/897ccb777dae8ee15049e625e58962e3722a4c47
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/examples/SO2_adaptor_example
/usr/examples/SO3_adaptor_example
/usr/examples/dynamic_pointcloud_example
/usr/examples/matrix_example
/usr/examples/pointcloud_adaptor_example
/usr/examples/pointcloud_example
/usr/examples/pointcloud_kdd_radius
/usr/examples/saveload_example
/usr/examples/vector_of_vectors_example

%files dev
%defattr(-,root,root,-)
/usr/include/nanoflann.hpp
/usr/lib64/cmake/nanoflann/nanoflannConfig.cmake
/usr/lib64/cmake/nanoflann/nanoflannConfigVersion.cmake
/usr/lib64/cmake/nanoflann/nanoflannTargets.cmake
/usr/lib64/pkgconfig/nanoflann.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nanoflann/525a4173096d5a839c3d609ae433ba90f2275dea
/usr/share/package-licenses/nanoflann/897ccb777dae8ee15049e625e58962e3722a4c47
